# coding: utf-8

"""
    Bob API

    Access your employees data with the Bob API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import os
from pprint import pprint
from hi_bob_python_sdk import HiBob

class TestSimple(unittest.TestCase):
    def setUp(self):
        pass

    def test_client(self):
        hibob = HiBob(
        
            username = 'YOUR_USERNAME',
            password = 'YOUR_PASSWORD',
        
                        bearer = 'YOUR_API_KEY',
        )
        self.assertIsNotNone(hibob)

    def tearDown(self):
        pass


if __name__ == "__main__":
    unittest.main()
