# coding: utf-8

"""
    Bob API

    Access your employees data with the Bob API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from hi_bob_python_sdk import schemas  # noqa: F401


class PeopleUpdateEmployeeRecordRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            firstName = schemas.StrSchema
        
            @staticmethod
            def personal() -> typing.Type['PeopleUpdateEmployeeRecordRequestPersonal']:
                return PeopleUpdateEmployeeRecordRequestPersonal
        
            @staticmethod
            def about() -> typing.Type['PeopleUpdateEmployeeRecordRequestAbout']:
                return PeopleUpdateEmployeeRecordRequestAbout
            __annotations__ = {
                "firstName": firstName,
                "personal": personal,
                "about": about,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["firstName"]) -> MetaOapg.properties.firstName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["personal"]) -> 'PeopleUpdateEmployeeRecordRequestPersonal': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["about"]) -> 'PeopleUpdateEmployeeRecordRequestAbout': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["firstName", "personal", "about", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["firstName"]) -> typing.Union[MetaOapg.properties.firstName, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["personal"]) -> typing.Union['PeopleUpdateEmployeeRecordRequestPersonal', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["about"]) -> typing.Union['PeopleUpdateEmployeeRecordRequestAbout', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["firstName", "personal", "about", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        firstName: typing.Union[MetaOapg.properties.firstName, str, schemas.Unset] = schemas.unset,
        personal: typing.Union['PeopleUpdateEmployeeRecordRequestPersonal', schemas.Unset] = schemas.unset,
        about: typing.Union['PeopleUpdateEmployeeRecordRequestAbout', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'PeopleUpdateEmployeeRecordRequest':
        return super().__new__(
            cls,
            *args,
            firstName=firstName,
            personal=personal,
            about=about,
            _configuration=_configuration,
            **kwargs,
        )

from hi_bob_python_sdk.model.people_update_employee_record_request_about import PeopleUpdateEmployeeRecordRequestAbout
from hi_bob_python_sdk.model.people_update_employee_record_request_personal import PeopleUpdateEmployeeRecordRequestPersonal
