# coding: utf-8

"""
    Bob API

    Access your employees data with the Bob API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from hi_bob_python_sdk import schemas  # noqa: F401


class ReadEmployeesRequestReference(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def fields() -> typing.Type['ReadEmployeesRequestReferenceFields']:
                return ReadEmployeesRequestReferenceFields
            
            
            class filters(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['EmployeeFilter']:
                        return EmployeeFilter
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['EmployeeFilter'], typing.List['EmployeeFilter']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'filters':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'EmployeeFilter':
                    return super().__getitem__(i)
            showInactive = schemas.BoolSchema
            humanReadable = schemas.StrSchema
            __annotations__ = {
                "fields": fields,
                "filters": filters,
                "showInactive": showInactive,
                "humanReadable": humanReadable,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["fields"]) -> 'ReadEmployeesRequestReferenceFields': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["filters"]) -> MetaOapg.properties.filters: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["showInactive"]) -> MetaOapg.properties.showInactive: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["humanReadable"]) -> MetaOapg.properties.humanReadable: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["fields", "filters", "showInactive", "humanReadable", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["fields"]) -> typing.Union['ReadEmployeesRequestReferenceFields', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["filters"]) -> typing.Union[MetaOapg.properties.filters, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["showInactive"]) -> typing.Union[MetaOapg.properties.showInactive, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["humanReadable"]) -> typing.Union[MetaOapg.properties.humanReadable, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["fields", "filters", "showInactive", "humanReadable", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        fields: typing.Union['ReadEmployeesRequestReferenceFields', schemas.Unset] = schemas.unset,
        filters: typing.Union[MetaOapg.properties.filters, list, tuple, schemas.Unset] = schemas.unset,
        showInactive: typing.Union[MetaOapg.properties.showInactive, bool, schemas.Unset] = schemas.unset,
        humanReadable: typing.Union[MetaOapg.properties.humanReadable, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ReadEmployeesRequestReference':
        return super().__new__(
            cls,
            *args,
            fields=fields,
            filters=filters,
            showInactive=showInactive,
            humanReadable=humanReadable,
            _configuration=_configuration,
            **kwargs,
        )

from hi_bob_python_sdk.model.employee_filter import EmployeeFilter
from hi_bob_python_sdk.model.read_employees_request_reference_fields import ReadEmployeesRequestReferenceFields
