# coding: utf-8

"""
    Bob API

    Access your employees data with the Bob API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from hi_bob_python_sdk import schemas  # noqa: F401


class VariableEntry(
    schemas.ComposedSchema,
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "amount",
            "paymentPeriod",
            "type",
        }
        
        
        class all_of_1(
            schemas.DictSchema
        ):
        
        
            class MetaOapg:
                
                class properties:
                
                    @staticmethod
                    def amount() -> typing.Type['CurrencyValue']:
                        return CurrencyValue
                    variableType = schemas.StrSchema
                    paymentPeriod = schemas.StrSchema
                    companyPercent = schemas.NumberSchema
                    departmentPercent = schemas.NumberSchema
                    individualPercent = schemas.NumberSchema
                    __annotations__ = {
                        "amount": amount,
                        "variableType": variableType,
                        "paymentPeriod": paymentPeriod,
                        "companyPercent": companyPercent,
                        "departmentPercent": departmentPercent,
                        "individualPercent": individualPercent,
                    }
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["amount"]) -> 'CurrencyValue': ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["variableType"]) -> MetaOapg.properties.variableType: ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["paymentPeriod"]) -> MetaOapg.properties.paymentPeriod: ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["companyPercent"]) -> MetaOapg.properties.companyPercent: ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["departmentPercent"]) -> MetaOapg.properties.departmentPercent: ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["individualPercent"]) -> MetaOapg.properties.individualPercent: ...
            
            @typing.overload
            def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
            
            def __getitem__(self, name: typing.Union[typing_extensions.Literal["amount", "variableType", "paymentPeriod", "companyPercent", "departmentPercent", "individualPercent", ], str]):
                # dict_instance[name] accessor
                return super().__getitem__(name)
            
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["amount"]) -> typing.Union['CurrencyValue', schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["variableType"]) -> typing.Union[MetaOapg.properties.variableType, schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["paymentPeriod"]) -> typing.Union[MetaOapg.properties.paymentPeriod, schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["companyPercent"]) -> typing.Union[MetaOapg.properties.companyPercent, schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["departmentPercent"]) -> typing.Union[MetaOapg.properties.departmentPercent, schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["individualPercent"]) -> typing.Union[MetaOapg.properties.individualPercent, schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
            
            def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["amount", "variableType", "paymentPeriod", "companyPercent", "departmentPercent", "individualPercent", ], str]):
                return super().get_item_oapg(name)
            
        
            def __new__(
                cls,
                *args: typing.Union[dict, frozendict.frozendict, ],
                amount: typing.Union['CurrencyValue', schemas.Unset] = schemas.unset,
                variableType: typing.Union[MetaOapg.properties.variableType, str, schemas.Unset] = schemas.unset,
                paymentPeriod: typing.Union[MetaOapg.properties.paymentPeriod, str, schemas.Unset] = schemas.unset,
                companyPercent: typing.Union[MetaOapg.properties.companyPercent, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
                departmentPercent: typing.Union[MetaOapg.properties.departmentPercent, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
                individualPercent: typing.Union[MetaOapg.properties.individualPercent, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
                _configuration: typing.Optional[schemas.Configuration] = None,
                **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
            ) -> 'all_of_1':
                return super().__new__(
                    cls,
                    *args,
                    amount=amount,
                    variableType=variableType,
                    paymentPeriod=paymentPeriod,
                    companyPercent=companyPercent,
                    departmentPercent=departmentPercent,
                    individualPercent=individualPercent,
                    _configuration=_configuration,
                    **kwargs,
                )
        
        @classmethod
        @functools.lru_cache()
        def all_of(cls):
            # we need this here to make our import statements work
            # we must store _composed_schemas in here so the code is only run
            # when we invoke this method. If we kept this at the class
            # level we would get an error because the class level
            # code would be run when this module is imported, and these composed
            # classes don't exist yet because their module has not finished
            # loading
            return [
                TableEntry,
                cls.all_of_1,
            ]

    
    amount: schemas.AnyTypeSchema
    paymentPeriod: schemas.AnyTypeSchema
    type: schemas.AnyTypeSchema

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'VariableEntry':
        return super().__new__(
            cls,
            *args,
            _configuration=_configuration,
            **kwargs,
        )

from hi_bob_python_sdk.model.currency_value import CurrencyValue
from hi_bob_python_sdk.model.table_entry import TableEntry
