# coding: utf-8

"""
    Bob API

    Access your employees data with the Bob API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from hi_bob_python_sdk.paths.people_custom_tables_employee_id_custom_table_id.post import CreateNewEntryRaw
from hi_bob_python_sdk.paths.people_custom_tables_employee_id_custom_table_id_entry_id.delete import DeleteEntryByIdRaw
from hi_bob_python_sdk.paths.people_custom_tables_employee_id_custom_table_id.get import ReadEntriesRaw
from hi_bob_python_sdk.paths.people_custom_tables_employee_id_custom_table_id_entry_id.put import UpdateEntryRaw


class CustomTablesApiRaw(
    CreateNewEntryRaw,
    DeleteEntryByIdRaw,
    ReadEntriesRaw,
    UpdateEntryRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
