# coding: utf-8

"""
    Bob API

    Access your employees data with the Bob API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from hi_bob_python_sdk.paths.people_custom_tables_employee_id_custom_table_id.post import CreateNewEntry
from hi_bob_python_sdk.paths.people_custom_tables_employee_id_custom_table_id_entry_id.delete import DeleteEntryById
from hi_bob_python_sdk.paths.people_custom_tables_employee_id_custom_table_id.get import ReadEntries
from hi_bob_python_sdk.paths.people_custom_tables_employee_id_custom_table_id_entry_id.put import UpdateEntry
from hi_bob_python_sdk.apis.tags.custom_tables_api_raw import CustomTablesApiRaw


class CustomTablesApi(
    CreateNewEntry,
    DeleteEntryById,
    ReadEntries,
    UpdateEntry,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: CustomTablesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = CustomTablesApiRaw(api_client)
