# coding: utf-8

"""
    Bob API

    Access your employees data with the Bob API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from hi_bob_python_sdk.paths.docs_people_id_confidential_doc_id.delete import DeleteEmployeeConfidentialDocRaw
from hi_bob_python_sdk.paths.docs_people_id.get import DownloadLinksRaw
from hi_bob_python_sdk.paths.docs_people_id_shared_doc_id.delete import RemoveEmployeeSharedDocumentRaw
from hi_bob_python_sdk.paths.docs_people_id_confidential_upload.post import UploadConfidentialFileRaw
from hi_bob_python_sdk.paths.docs_people_id_confidential.post import UploadToConfidentialFolderRaw
from hi_bob_python_sdk.paths.docs_people_id_shared.post import UploadToSharedFolderRaw
from hi_bob_python_sdk.paths.docs_people_id_shared_upload.post import UploadToSharedFolder0Raw


class DocumentsApiRaw(
    DeleteEmployeeConfidentialDocRaw,
    DownloadLinksRaw,
    RemoveEmployeeSharedDocumentRaw,
    UploadConfidentialFileRaw,
    UploadToConfidentialFolderRaw,
    UploadToSharedFolderRaw,
    UploadToSharedFolder0Raw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
