# coding: utf-8

"""
    Bob API

    Access your employees data with the Bob API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from hi_bob_python_sdk.paths.company_people_fields.post import AddNewFieldRaw
from hi_bob_python_sdk.paths.company_named_lists_list_name.post import AddNewItemToNamedListRaw
from hi_bob_python_sdk.paths.company_people_fields_field_id.delete import DeleteFieldRaw
from hi_bob_python_sdk.paths.company_named_lists_list_name_item_id.delete import DeleteItemFromCompanyNamedListRaw
from hi_bob_python_sdk.paths.company_people_fields.get import GetCompanyFieldsRaw
from hi_bob_python_sdk.paths.company_named_lists.get import GetCompanyNamedListsRaw
from hi_bob_python_sdk.paths.people_custom_tables_metadata.get import GetCustomTableMetadataRaw
from hi_bob_python_sdk.paths.company_named_lists_list_name.get import GetNamedListRaw
from hi_bob_python_sdk.paths.metadata_objects_position.get import GetPositionFieldsRaw
from hi_bob_python_sdk.paths.people_custom_tables_metadata_custom_table_id.get import GetTableDetailsRaw
from hi_bob_python_sdk.paths.company_people_fields_field_id.put import UpdateFieldRaw
from hi_bob_python_sdk.paths.company_named_lists_list_name_item_id.put import UpdateItemFromNamedListRaw


class MetadataApiRaw(
    AddNewFieldRaw,
    AddNewItemToNamedListRaw,
    DeleteFieldRaw,
    DeleteItemFromCompanyNamedListRaw,
    GetCompanyFieldsRaw,
    GetCompanyNamedListsRaw,
    GetCustomTableMetadataRaw,
    GetNamedListRaw,
    GetPositionFieldsRaw,
    GetTableDetailsRaw,
    UpdateFieldRaw,
    UpdateItemFromNamedListRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
