# coding: utf-8

"""
    Bob API

    Access your employees data with the Bob API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from hi_bob_python_sdk.paths.onboarding_wizards.get import GetWizardSummary
from hi_bob_python_sdk.apis.tags.onboarding_api_raw import OnboardingApiRaw


class OnboardingApi(
    GetWizardSummary,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: OnboardingApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = OnboardingApiRaw(api_client)
