# coding: utf-8

"""
    Bob API

    Access your employees data with the Bob API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from hi_bob_python_sdk.paths.people_id_equities.post import CreateEquityGrantRaw
from hi_bob_python_sdk.paths.people_id_salaries.post import CreateNewSalaryEntryRaw
from hi_bob_python_sdk.paths.people_id_training.post import CreateTrainingRecordRaw
from hi_bob_python_sdk.paths.people_id_variable.post import CreateVariablePaymentRaw
from hi_bob_python_sdk.paths.people_id_equities_entry_id.delete import DeleteEquityGrantRaw
from hi_bob_python_sdk.paths.people_id_salaries_entry_id.delete import DeleteSalaryEntryRaw
from hi_bob_python_sdk.paths.people_id_variable_entry_id.delete import DeleteTrainingRecordRaw
from hi_bob_python_sdk.paths.people_id_training_entry_id.delete import DeleteTrainingRecord0Raw
from hi_bob_python_sdk.paths.people_id_salaries.get import GetSalaryHistoryRaw
from hi_bob_python_sdk.paths.people_id_equities.get import ListEquityGrantsRaw
from hi_bob_python_sdk.paths.people_id_training.get import ListTrainingRecordsRaw
from hi_bob_python_sdk.paths.people_id_variable.get import ListVariablePaymentsRaw
from hi_bob_python_sdk.paths.payroll_history.get import ReadHistoryRaw
from hi_bob_python_sdk.paths.people_id_equities_entry_id.put import UpdateEquityGrantForEmployeeRaw


class PayrollApiRaw(
    CreateEquityGrantRaw,
    CreateNewSalaryEntryRaw,
    CreateTrainingRecordRaw,
    CreateVariablePaymentRaw,
    DeleteEquityGrantRaw,
    DeleteSalaryEntryRaw,
    DeleteTrainingRecordRaw,
    DeleteTrainingRecord0Raw,
    GetSalaryHistoryRaw,
    ListEquityGrantsRaw,
    ListTrainingRecordsRaw,
    ListVariablePaymentsRaw,
    ReadHistoryRaw,
    UpdateEquityGrantForEmployeeRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
