# coding: utf-8

"""
    Bob API

    Access your employees data with the Bob API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from hi_bob_python_sdk.paths.people_id_equities.post import CreateEquityGrant
from hi_bob_python_sdk.paths.people_id_salaries.post import CreateNewSalaryEntry
from hi_bob_python_sdk.paths.people_id_training.post import CreateTrainingRecord
from hi_bob_python_sdk.paths.people_id_variable.post import CreateVariablePayment
from hi_bob_python_sdk.paths.people_id_equities_entry_id.delete import DeleteEquityGrant
from hi_bob_python_sdk.paths.people_id_salaries_entry_id.delete import DeleteSalaryEntry
from hi_bob_python_sdk.paths.people_id_variable_entry_id.delete import DeleteTrainingRecord
from hi_bob_python_sdk.paths.people_id_training_entry_id.delete import DeleteTrainingRecord0
from hi_bob_python_sdk.paths.people_id_salaries.get import GetSalaryHistory
from hi_bob_python_sdk.paths.people_id_equities.get import ListEquityGrants
from hi_bob_python_sdk.paths.people_id_training.get import ListTrainingRecords
from hi_bob_python_sdk.paths.people_id_variable.get import ListVariablePayments
from hi_bob_python_sdk.paths.payroll_history.get import ReadHistory
from hi_bob_python_sdk.paths.people_id_equities_entry_id.put import UpdateEquityGrantForEmployee
from hi_bob_python_sdk.apis.tags.payroll_api_raw import PayrollApiRaw


class PayrollApi(
    CreateEquityGrant,
    CreateNewSalaryEntry,
    CreateTrainingRecord,
    CreateVariablePayment,
    DeleteEquityGrant,
    DeleteSalaryEntry,
    DeleteTrainingRecord,
    DeleteTrainingRecord0,
    GetSalaryHistory,
    ListEquityGrants,
    ListTrainingRecords,
    ListVariablePayments,
    ReadHistory,
    UpdateEquityGrantForEmployee,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: PayrollApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = PayrollApiRaw(api_client)
