# coding: utf-8

"""
    Bob API

    Access your employees data with the Bob API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from hi_bob_python_sdk.paths.company_reports_report_id_download.get import DownloadById
from hi_bob_python_sdk.paths.company_reports_download_report_name.get import DownloadReportFile
from hi_bob_python_sdk.paths.company_reports_report_id_download_async.get import GetDownloadUrl
from hi_bob_python_sdk.paths.company_reports.get import ListAccessibleReports
from hi_bob_python_sdk.apis.tags.reports_api_raw import ReportsApiRaw


class ReportsApi(
    DownloadById,
    DownloadReportFile,
    GetDownloadUrl,
    ListAccessibleReports,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ReportsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ReportsApiRaw(api_client)
