# coding: utf-8

"""
    Bob API

    Access your employees data with the Bob API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from hi_bob_python_sdk.paths.company_reports_report_id_download.get import DownloadByIdRaw
from hi_bob_python_sdk.paths.company_reports_download_report_name.get import DownloadReportFileRaw
from hi_bob_python_sdk.paths.company_reports_report_id_download_async.get import GetDownloadUrlRaw
from hi_bob_python_sdk.paths.company_reports.get import ListAccessibleReportsRaw


class ReportsApiRaw(
    DownloadByIdRaw,
    DownloadReportFileRaw,
    GetDownloadUrlRaw,
    ListAccessibleReportsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
