# coding: utf-8

"""
    Bob API

    Access your employees data with the Bob API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from hi_bob_python_sdk.paths.tasks_task_id_complete.post import CompleteTaskRaw
from hi_bob_python_sdk.paths.my_tasks.get import GetEmployeeTasksRaw
from hi_bob_python_sdk.paths.tasks.get import GetOpenTasksRaw
from hi_bob_python_sdk.paths.tasks_people_id.get import ReadEmployeeTasksRaw


class TasksApiRaw(
    CompleteTaskRaw,
    GetEmployeeTasksRaw,
    GetOpenTasksRaw,
    ReadEmployeeTasksRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
