# coding: utf-8

"""
    Bob API

    Access your employees data with the Bob API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from hi_bob_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from hi_bob_python_sdk.api_response import AsyncGeneratorResponse
from hi_bob_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from hi_bob_python_sdk import schemas  # noqa: F401

from hi_bob_python_sdk.model.error import Error as ErrorSchema
from hi_bob_python_sdk.model.out_todays import OutTodays as OutTodaysSchema

from hi_bob_python_sdk.type.error import Error
from hi_bob_python_sdk.type.out_todays import OutTodays

from ...api_client import Dictionary
from hi_bob_python_sdk.pydantic.error import Error as ErrorPydantic
from hi_bob_python_sdk.pydantic.out_todays import OutTodays as OutTodaysPydantic

from . import path

# Query params
TodaySchema = schemas.DateSchema
IncludeHourlySchema = schemas.BoolSchema
IncludePrivateSchema = schemas.BoolSchema
SiteIdSchema = schemas.IntSchema
RequestRequiredQueryParams = typing_extensions.TypedDict(
    'RequestRequiredQueryParams',
    {
    }
)
RequestOptionalQueryParams = typing_extensions.TypedDict(
    'RequestOptionalQueryParams',
    {
        'today': typing.Union[TodaySchema, str, date, ],
        'includeHourly': typing.Union[IncludeHourlySchema, bool, ],
        'includePrivate': typing.Union[IncludePrivateSchema, bool, ],
        'siteId': typing.Union[SiteIdSchema, decimal.Decimal, int, ],
    },
    total=False
)


class RequestQueryParams(RequestRequiredQueryParams, RequestOptionalQueryParams):
    pass


request_query_today = api_client.QueryParameter(
    name="today",
    style=api_client.ParameterStyle.FORM,
    schema=TodaySchema,
    explode=True,
)
request_query_include_hourly = api_client.QueryParameter(
    name="includeHourly",
    style=api_client.ParameterStyle.FORM,
    schema=IncludeHourlySchema,
    explode=True,
)
request_query_include_private = api_client.QueryParameter(
    name="includePrivate",
    style=api_client.ParameterStyle.FORM,
    schema=IncludePrivateSchema,
    explode=True,
)
request_query_site_id = api_client.QueryParameter(
    name="siteId",
    style=api_client.ParameterStyle.FORM,
    schema=SiteIdSchema,
    explode=True,
)
_auth = [
    'Basic',
]
SchemaFor200ResponseBodyApplicationJson = OutTodaysSchema


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    body: OutTodays


@dataclass
class ApiResponseFor200Async(api_client.AsyncApiResponse):
    body: OutTodays


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    response_cls_async=ApiResponseFor200Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJson),
    },
)
SchemaFor0ResponseBodyApplicationJson = ErrorSchema


@dataclass
class ApiResponseForDefault(api_client.ApiResponse):
    body: Error


@dataclass
class ApiResponseForDefaultAsync(api_client.AsyncApiResponse):
    body: Error


_response_for_default = api_client.OpenApiResponse(
    response_cls=ApiResponseForDefault,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor0ResponseBodyApplicationJson),
    },
)
_status_code_to_response = {
    '200': _response_for_200,
    'default': _response_for_default,
}
_all_accept_content_types = (
    'application/json',
)


class BaseApi(api_client.Api):

    def _get_out_of_office_mapped_args(
        self,
        today: typing.Optional[date] = None,
        include_hourly: typing.Optional[bool] = None,
        include_private: typing.Optional[bool] = None,
        site_id: typing.Optional[int] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _query_params = {}
        if today is not None:
            _query_params["today"] = today
        if include_hourly is not None:
            _query_params["includeHourly"] = include_hourly
        if include_private is not None:
            _query_params["includePrivate"] = include_private
        if site_id is not None:
            _query_params["siteId"] = site_id
        args.query = _query_params
        return args

    async def _aget_out_of_office_oapg(
        self,
            query_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        ApiResponseForDefaultAsync,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        Read a list of who&#x27;s out of the office today or on the specified date.
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        used_path = path.value
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_today,
            request_query_include_hourly,
            request_query_include_private,
            request_query_site_id,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'get'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/timeoff/outtoday',
            auth_settings=_auth,
            headers=_headers,
        )
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            auth_settings=_auth,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            default_response = _status_code_to_response.get('default')
            if default_response:
                api_response = default_response.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
            else:
                api_response = api_client.ApiResponseWithoutDeserializationAsync(
                    response=response.http_response,
                    round_trip_time=response.round_trip_time,
                    status=response.http_response.status,
                    headers=response.http_response.headers,
                )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _get_out_of_office_oapg(
        self,
            query_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        ApiResponseForDefault,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        Read a list of who&#x27;s out of the office today or on the specified date.
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        used_path = path.value
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_today,
            request_query_include_hourly,
            request_query_include_private,
            request_query_site_id,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'get'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/timeoff/outtoday',
            auth_settings=_auth,
            headers=_headers,
        )
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            auth_settings=_auth,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            default_response = _status_code_to_response.get('default')
            if default_response:
                api_response = default_response.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
            else:
                api_response = api_client.ApiResponseWithoutDeserialization(
                    response=response.http_response,
                    round_trip_time=response.round_trip_time,
                    status=response.http_response.status,
                    headers=response.http_response.headers,
                )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class GetOutOfOfficeRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def aget_out_of_office(
        self,
        today: typing.Optional[date] = None,
        include_hourly: typing.Optional[bool] = None,
        include_private: typing.Optional[bool] = None,
        site_id: typing.Optional[int] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        ApiResponseForDefaultAsync,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._get_out_of_office_mapped_args(
            today=today,
            include_hourly=include_hourly,
            include_private=include_private,
            site_id=site_id,
        )
        return await self._aget_out_of_office_oapg(
            query_params=args.query,
            **kwargs,
        )
    
    def get_out_of_office(
        self,
        today: typing.Optional[date] = None,
        include_hourly: typing.Optional[bool] = None,
        include_private: typing.Optional[bool] = None,
        site_id: typing.Optional[int] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        ApiResponseForDefault,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._get_out_of_office_mapped_args(
            today=today,
            include_hourly=include_hourly,
            include_private=include_private,
            site_id=site_id,
        )
        return self._get_out_of_office_oapg(
            query_params=args.query,
        )

class GetOutOfOffice(BaseApi):

    async def aget_out_of_office(
        self,
        today: typing.Optional[date] = None,
        include_hourly: typing.Optional[bool] = None,
        include_private: typing.Optional[bool] = None,
        site_id: typing.Optional[int] = None,
        validate: bool = False,
        **kwargs,
    ) -> OutTodaysPydantic:
        raw_response = await self.raw.aget_out_of_office(
            today=today,
            include_hourly=include_hourly,
            include_private=include_private,
            site_id=site_id,
            **kwargs,
        )
        if validate:
            return OutTodaysPydantic(**raw_response.body)
        return api_client.construct_model_instance(OutTodaysPydantic, raw_response.body)
    
    
    def get_out_of_office(
        self,
        today: typing.Optional[date] = None,
        include_hourly: typing.Optional[bool] = None,
        include_private: typing.Optional[bool] = None,
        site_id: typing.Optional[int] = None,
        validate: bool = False,
    ) -> OutTodaysPydantic:
        raw_response = self.raw.get_out_of_office(
            today=today,
            include_hourly=include_hourly,
            include_private=include_private,
            site_id=site_id,
        )
        if validate:
            return OutTodaysPydantic(**raw_response.body)
        return api_client.construct_model_instance(OutTodaysPydantic, raw_response.body)


class ApiForget(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def aget(
        self,
        today: typing.Optional[date] = None,
        include_hourly: typing.Optional[bool] = None,
        include_private: typing.Optional[bool] = None,
        site_id: typing.Optional[int] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        ApiResponseForDefaultAsync,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._get_out_of_office_mapped_args(
            today=today,
            include_hourly=include_hourly,
            include_private=include_private,
            site_id=site_id,
        )
        return await self._aget_out_of_office_oapg(
            query_params=args.query,
            **kwargs,
        )
    
    def get(
        self,
        today: typing.Optional[date] = None,
        include_hourly: typing.Optional[bool] = None,
        include_private: typing.Optional[bool] = None,
        site_id: typing.Optional[int] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        ApiResponseForDefault,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._get_out_of_office_mapped_args(
            today=today,
            include_hourly=include_hourly,
            include_private=include_private,
            site_id=site_id,
        )
        return self._get_out_of_office_oapg(
            query_params=args.query,
        )

