# coding: utf-8

"""
    Bob API

    Access your employees data with the Bob API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import hi_bob_python_sdk
from hi_bob_python_sdk.model.read_employees_request_reference_fields import ReadEmployeesRequestReferenceFields
from hi_bob_python_sdk import configuration


class TestReadEmployeesRequestReferenceFields(unittest.TestCase):
    """ReadEmployeesRequestReferenceFields unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
