# coding: utf-8

"""
    Bob API

    Access your employees data with the Bob API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from hi_bob_python_sdk.pydantic.employee_filter_values import EmployeeFilterValues

class EmployeeFilter(BaseModel):
    # The field id (path) to filter by.<br /> Supported fields: “root.id”, \"root.email\".<br />Any other path will get a response of 400 HTTP error.
    field_path: typing.Optional[str] = Field(None, alias='fieldPath')

    # Supported operators: “equals” <br /> Any other operator will get a response of 400 HTTP error.
    operator: typing.Optional[str] = Field(None, alias='operator')

    values: typing.Optional[EmployeeFilterValues] = Field(None, alias='values')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
