# coding: utf-8

"""
    Bob API

    Access your employees data with the Bob API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from hi_bob_python_sdk.pydantic.employee_termination_notice_period import EmployeeTerminationNoticePeriod

class EmployeeTermination(BaseModel):
    # The employee's termination date
    termination_date: date = Field(alias='terminationDate')

    # The ID of the 'terminationReason' list entry
    termination_reason: typing.Optional[str] = Field(None, alias='terminationReason')

    # The ID of the 'lifecycleReasonType' list entry
    reason_type: typing.Optional[str] = Field(None, alias='reasonType')

    notice_period: typing.Optional[EmployeeTerminationNoticePeriod] = Field(None, alias='noticePeriod')

    last_day_of_work: typing.Optional[date] = Field(None, alias='lastDayOfWork')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
