# coding: utf-8

"""
    Bob API

    Access your employees data with the Bob API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class FilterInstruction(BaseModel):
    # The field id (path) to filter by.<br /> Supported fields: “/position/status”, \"/position/name\".<br />Any other path will get a response of 400 HTTP error.
    field_id: str = Field(alias='fieldId')

    # Supported operators: “equals”, \"notEqual\".<br />Any other operator will get a response of 400 HTTP error.
    operator: str = Field(alias='operator')

    # List of values to compare.<br />Empty list will result in 400 HTTP error.
    values: typing.List[str] = Field(alias='values')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
