# coding: utf-8

"""
    Bob API

    Access your employees data with the Bob API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from hi_bob_python_sdk.pydantic.import_attendance_response_errors import ImportAttendanceResponseErrors

class ImportAttendanceResponse(BaseModel):
    # Import status
    status: typing.Optional[Literal["success", "failed", "partial_success"]] = Field(None, alias='status')

    # Total number of clock-in and clock-out events received
    total: typing.Optional[typing.Union[int, float]] = Field(None, alias='total')

    # Number of clock-in/clock-out events imported
    imported: typing.Optional[typing.Union[int, float]] = Field(None, alias='imported')

    # Number of clock-in/clock-out events which were not imported
    not_imported: typing.Optional[typing.Union[int, float]] = Field(None, alias='notImported')

    errors: typing.Optional[ImportAttendanceResponseErrors] = Field(None, alias='errors')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
