# coding: utf-8

"""
    Bob API

    Access your employees data with the Bob API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class ObjectsMetadataJsonPath(BaseModel):
    # The path to the field json object. The field value and other properties, such as humanReadable value, will be placed inside.
    root: typing.Optional[str] = Field(None, alias='root')

    # The path to the actual field value.
    raw_data: typing.Optional[str] = Field(None, alias='rawData')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
