# coding: utf-8

"""
    Bob API

    Access your employees data with the Bob API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class TableEntry(BaseModel):
    # The date this entry becomes effective.
    effective_date: date = Field(alias='effectiveDate')

    # ID.
    id: typing.Optional[int] = Field(None, alias='id')

    # The reason for this change.
    reason: typing.Optional[str] = Field(None, alias='reason')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
