# do not import all endpoints into this module because that uses a lot of memory and stack frames
# if you need the ability to import all endpoints from this module, import them with
# from hi_bob_python_sdk.apis.path_to_api import path_to_api

import enum


class PathValues(str, enum.Enum):
    PEOPLE_SEARCH = "/people/search"
    PEOPLE = "/people"
    PEOPLE_IDENTIFIER = "/people/{identifier}"
    EMPLOYEES_IDENTIFIER_UNINVITE = "/employees/{identifier}/uninvite"
    EMPLOYEES_IDENTIFIER_TERMINATE = "/employees/{identifier}/terminate"
    ONBOARDING_WIZARDS = "/onboarding/wizards"
    EMPLOYEES_EMPLOYEE_ID_INVITATIONS = "/employees/{employeeId}/invitations"
    EMPLOYEES_EMPLOYEE_ID_STARTDATE = "/employees/{employeeId}/start-date"
    COMPANY_REPORTS = "/company/reports"
    COMPANY_REPORTS_REPORT_ID_DOWNLOAD = "/company/reports/{reportId}/download"
    COMPANY_REPORTS_REPORT_ID_DOWNLOADASYNC = "/company/reports/{reportId}/download-async"
    COMPANY_REPORTS_DOWNLOAD_REPORT_NAME = "/company/reports/download/{reportName}"
    PROFILES = "/profiles"
    AVATARS = "/avatars"
    AVATARS_EMPLOYEE_ID = "/avatars/{employeeId}"
    MY_AVATAR = "/my/avatar"
    TASKS = "/tasks"
    MY_TASKS = "/my/tasks"
    TASKS_PEOPLE_ID = "/tasks/people/{id}"
    TASKS_TASK_ID_COMPLETE = "/tasks/{taskId}/complete"
    PEOPLE_ID_EMAIL = "/people/{id}/email"
    COMPANY_NAMEDLISTS = "/company/named-lists"
    COMPANY_NAMEDLISTS_LIST_NAME = "/company/named-lists/{listName}"
    COMPANY_NAMEDLISTS_LIST_NAME_ITEM_ID = "/company/named-lists/{listName}/{itemId}"
    COMPANY_PEOPLE_FIELDS = "/company/people/fields"
    COMPANY_PEOPLE_FIELDS_FIELD_ID = "/company/people/fields/{fieldId}"
    TIMEOFF_EMPLOYEES_ID_REQUESTS = "/timeoff/employees/{id}/requests"
    TIMEOFF_EMPLOYEES_ID_DIFF_HOURS_REQUESTS = "/timeoff/employees/{id}/diffHours/requests"
    TIMEOFF_EMPLOYEES_ID_REQUESTS_REQUEST_ID = "/timeoff/employees/{id}/requests/{requestId}"
    TIMEOFF_REQUESTS_CHANGES = "/timeoff/requests/changes"
    TIMEOFF_WHOSOUT = "/timeoff/whosout"
    TIMEOFF_OUTTODAY = "/timeoff/outtoday"
    TIMEOFF_POLICYTYPES_POLICY_TYPE_REASONCODES = "/timeoff/policy-types/{policyType}/reason-codes"
    TIMEOFF_POLICYTYPES_POLICY_TYPE = "/timeoff/policy-types/{policyType}"
    TIMEOFF_POLICYTYPES = "/timeoff/policy-types"
    TIMEOFF_POLICIES = "/timeoff/policies"
    TIMEOFF_POLICIES_NAMES = "/timeoff/policies/names"
    TIMEOFF_EMPLOYEES_ID_BALANCE = "/timeoff/employees/{id}/balance"
    TIMEOFF_EMPLOYEES_ID_ADJUSTMENTS = "/timeoff/employees/{id}/adjustments"
    ATTENDANCE_IMPORT_IMPORT_METHOD = "/attendance/import/{importMethod}"
    PAYROLL_HISTORY = "/payroll/history"
    DOCS_PEOPLE_ID_SHARED = "/docs/people/{id}/shared"
    DOCS_PEOPLE_ID_CONFIDENTIAL = "/docs/people/{id}/confidential"
    DOCS_PEOPLE_ID_SHARED_UPLOAD = "/docs/people/{id}/shared/upload"
    DOCS_PEOPLE_ID_CONFIDENTIAL_UPLOAD = "/docs/people/{id}/confidential/upload"
    DOCS_PEOPLE_ID_SHARED_DOC_ID = "/docs/people/{id}/shared/{docId}"
    DOCS_PEOPLE_ID_CONFIDENTIAL_DOC_ID = "/docs/people/{id}/confidential/{docId}"
    DOCS_PEOPLE_ID = "/docs/people/{id}"
    PEOPLE_ID_WORK = "/people/{id}/work"
    PEOPLE_ID_WORK_ENTRY_ID = "/people/{id}/work/{entry_id}"
    PEOPLE_ID_EMPLOYMENT = "/people/{id}/employment"
    PEOPLE_ID_EMPLOYMENT_ENTRY_ID = "/people/{id}/employment/{entry_id}"
    PEOPLE_ID_LIFECYCLE = "/people/{id}/lifecycle"
    PEOPLE_ID_SALARIES = "/people/{id}/salaries"
    PEOPLE_ID_SALARIES_ENTRY_ID = "/people/{id}/salaries/{entry_id}"
    PEOPLE_ID_EQUITIES = "/people/{id}/equities"
    PEOPLE_ID_EQUITIES_ENTRY_ID = "/people/{id}/equities/{entry_id}"
    PEOPLE_ID_VARIABLE = "/people/{id}/variable"
    PEOPLE_ID_VARIABLE_ENTRY_ID = "/people/{id}/variable/{entry_id}"
    PEOPLE_ID_TRAINING = "/people/{id}/training"
    PEOPLE_ID_TRAINING_ENTRY_ID = "/people/{id}/training/{entry_id}"
    PEOPLE_CUSTOMTABLES_METADATA = "/people/custom-tables/metadata"
    PEOPLE_CUSTOMTABLES_METADATA_CUSTOM_TABLE_ID = "/people/custom-tables/metadata/{custom_table_id}"
    PEOPLE_CUSTOMTABLES_EMPLOYEE_ID_CUSTOM_TABLE_ID = "/people/custom-tables/{employee_id}/{custom_table_id}"
    PEOPLE_CUSTOMTABLES_EMPLOYEE_ID_CUSTOM_TABLE_ID_ENTRY_ID = "/people/custom-tables/{employee_id}/{custom_table_id}/{entry_id}"
    METADATA_OBJECTS_POSITION = "/metadata/objects/position"
    OBJECTS_POSITION_SEARCH = "/objects/position/search"
