# coding: utf-8
"""
    Bob API

    Access your employees data with the Bob API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import typing
import inspect
from datetime import date, datetime
from hi_bob_python_sdk.client_custom import ClientCustom
from hi_bob_python_sdk.configuration import Configuration
from hi_bob_python_sdk.api_client import ApiClient
from hi_bob_python_sdk.type_util import copy_signature
from hi_bob_python_sdk.apis.tags.attendance_api import AttendanceApi
from hi_bob_python_sdk.apis.tags.custom_tables_api import CustomTablesApi
from hi_bob_python_sdk.apis.tags.documents_api import DocumentsApi
from hi_bob_python_sdk.apis.tags.metadata_api import MetadataApi
from hi_bob_python_sdk.apis.tags.objects_api import ObjectsApi
from hi_bob_python_sdk.apis.tags.onboarding_api import OnboardingApi
from hi_bob_python_sdk.apis.tags.payroll_api import PayrollApi
from hi_bob_python_sdk.apis.tags.people_api import PeopleApi
from hi_bob_python_sdk.apis.tags.reports_api import ReportsApi
from hi_bob_python_sdk.apis.tags.tables_api import TablesApi
from hi_bob_python_sdk.apis.tags.tasks_api import TasksApi
from hi_bob_python_sdk.apis.tags.time_off_api import TimeOffApi



class HiBob(ClientCustom):

    def __init__(self, configuration: typing.Union[Configuration, None] = None, **kwargs):
        super().__init__(configuration, **kwargs)
        if (len(kwargs) > 0):
            configuration = Configuration(**kwargs)
        if (configuration is None):
            raise Exception("configuration is required")
        api_client = ApiClient(configuration)
        self.attendance: AttendanceApi = AttendanceApi(api_client)
        self.custom_tables: CustomTablesApi = CustomTablesApi(api_client)
        self.documents: DocumentsApi = DocumentsApi(api_client)
        self.metadata: MetadataApi = MetadataApi(api_client)
        self.objects: ObjectsApi = ObjectsApi(api_client)
        self.onboarding: OnboardingApi = OnboardingApi(api_client)
        self.payroll: PayrollApi = PayrollApi(api_client)
        self.people: PeopleApi = PeopleApi(api_client)
        self.reports: ReportsApi = ReportsApi(api_client)
        self.tables: TablesApi = TablesApi(api_client)
        self.tasks: TasksApi = TasksApi(api_client)
        self.time_off: TimeOffApi = TimeOffApi(api_client)
