# coding: utf-8

"""
    Bob API

    Access your employees data with the Bob API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest
from unittest.mock import patch

import urllib3

import hi_bob_python_sdk
from hi_bob_python_sdk.paths.timeoff_policy_types_policy_type import get
from hi_bob_python_sdk import configuration, schemas, api_client

from .. import ApiTestMixin


class TestTimeoffPolicyTypesPolicyType(ApiTestMixin, unittest.TestCase):
    """
    TimeoffPolicyTypesPolicyType unit test stubs
        Get Policy type details
    """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    response_status = 200




if __name__ == '__main__':
    unittest.main()
