# coding: utf-8

"""
    Bob API

    Access your employees data with the Bob API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredAdjustmentRequest(TypedDict):
    pass

class OptionalAdjustmentRequest(TypedDict, total=False):
    # Adjustment type - balance or time used.
    adjustmentType: str

    # Policy type name.
    policyType: str

    # The date this adjustment becomes effective.
    effectiveDate: date

    # The amount of days/hours to add/subtract.
    amount: typing.Union[int, float]

    # A reason for this adjustment.
    reason: str

class AdjustmentRequest(RequiredAdjustmentRequest, OptionalAdjustmentRequest):
    pass
