# coding: utf-8

"""
    Bob API

    Access your employees data with the Bob API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredCreateEmployeeRequestWork(TypedDict):
    # The employee's site.
    site: str

    # The employee's employment start date
    startDate: date

class OptionalCreateEmployeeRequestWork(TypedDict, total=False):
    pass

class CreateEmployeeRequestWork(RequiredCreateEmployeeRequestWork, OptionalCreateEmployeeRequestWork):
    pass
