# coding: utf-8

"""
    Bob API

    Access your employees data with the Bob API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredEmployeeDocumentWithDownloadLink(TypedDict):
    pass

class OptionalEmployeeDocumentWithDownloadLink(TypedDict, total=False):
    # The name of the document.
    documentName: str

    # The name of the document.
    downloadLink: str

class EmployeeDocumentWithDownloadLink(RequiredEmployeeDocumentWithDownloadLink, OptionalEmployeeDocumentWithDownloadLink):
    pass
