# coding: utf-8

"""
    Bob API

    Access your employees data with the Bob API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from hi_bob_python_sdk.type.employee_filter_values import EmployeeFilterValues

class RequiredEmployeeFilter(TypedDict):
    pass

class OptionalEmployeeFilter(TypedDict, total=False):
    # The field id (path) to filter by.<br /> Supported fields: “root.id”, \"root.email\".<br />Any other path will get a response of 400 HTTP error.
    fieldPath: str

    # Supported operators: “equals” <br /> Any other operator will get a response of 400 HTTP error.
    operator: str

    values: EmployeeFilterValues

class EmployeeFilter(RequiredEmployeeFilter, OptionalEmployeeFilter):
    pass
