# coding: utf-8

"""
    Bob API

    Access your employees data with the Bob API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from hi_bob_python_sdk.type.list_item import ListItem

class RequiredModelList(TypedDict):
    pass

class OptionalModelList(TypedDict, total=False):
    # The name of the list
    name: str

    # The elements in the list.
    items: typing.List[ListItem]

class ModelList(RequiredModelList, OptionalModelList):
    pass
