# coding: utf-8

"""
    Bob API

    Access your employees data with the Bob API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from hi_bob_python_sdk.type.objects_metadata_field_type import ObjectsMetadataFieldType
from hi_bob_python_sdk.type.objects_metadata_json_path import ObjectsMetadataJsonPath

class RequiredObjectsMetadata(TypedDict):
    pass

class OptionalObjectsMetadata(TypedDict, total=False):
    # Description of the field.
    description: str

    # ID of the field.
    id: str

    # Name of the field.
    name: str

    fieldType: ObjectsMetadataFieldType

    jsonPath: ObjectsMetadataJsonPath

class ObjectsMetadata(RequiredObjectsMetadata, OptionalObjectsMetadata):
    pass
