# coding: utf-8

"""
    Bob API

    Access your employees data with the Bob API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredOutToday(TypedDict):
    pass

class OptionalOutToday(TypedDict, total=False):
    # Employee ID.
    employeeId: str

    # Employee display name.
    employeeDisplayName: str

    # Employee email address.
    employeeEmail: str

    # Display name of the policy type.
    policyTypeDisplayName: str

    # Date of the first day of the time off (not relevant for requests using the hours type).
    startDate: date

    # What portion of the first day is included - all_day, morning or afternoon (relevant for request using the days type).
    startDatePortion: str

    # Date of the last day of the time off (not relevant for requests using the hours type).
    endDate: date

    # What portion of the last day is included - all_day, morning or afternoon (relevant for request using the days type).
    endDatePortion: str

    # The type of request duration.<br> <b>portionOnRange</b> is when the request is for every morning or every afternoon during the days requested.<br> <b>hoursOnRange</b> is when the request is for X hours every day during the days requested.
    requestRangeType: str

    # What portion of the request's days is included - morning or afternoon (relevant for request using the portionOnRange type).
    dayPortion: str

    # The time off duration in hours for every request's days (relevant for requests with hoursOnRange type).
    dailyHours: typing.Union[int, float]

    # Date of the time off (relevant for requests using the hours type).
    date: date

    # The time off duration in hours for the date (relevant for requests with hours type).
    hours: int

    # Relevant for requests using the hours type.
    minutes: int

class OutToday(RequiredOutToday, OptionalOutToday):
    pass
