# coding: utf-8

"""
    Bob API

    Access your employees data with the Bob API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from hi_bob_python_sdk.type.people_update_employee_record_request_about import PeopleUpdateEmployeeRecordRequestAbout
from hi_bob_python_sdk.type.people_update_employee_record_request_personal import PeopleUpdateEmployeeRecordRequestPersonal

class RequiredPeopleUpdateEmployeeRecordRequest(TypedDict):
    pass

class OptionalPeopleUpdateEmployeeRecordRequest(TypedDict, total=False):
    firstName: str

    personal: PeopleUpdateEmployeeRecordRequestPersonal

    about: PeopleUpdateEmployeeRecordRequestAbout

class PeopleUpdateEmployeeRecordRequest(RequiredPeopleUpdateEmployeeRecordRequest, OptionalPeopleUpdateEmployeeRecordRequest):
    pass
