# coding: utf-8

"""
    Bob API

    Access your employees data with the Bob API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredPolicyType(TypedDict):
    pass

class OptionalPolicyType(TypedDict, total=False):
    name: str

    # Activity type.
    activity: str

    # Requests will be deducted from the balance only for working days.
    bookingWorkDaysOnly: bool

    unit: str

class PolicyType(RequiredPolicyType, OptionalPolicyType):
    pass
