# coding: utf-8

"""
    Bob API

    Access your employees data with the Bob API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from hi_bob_python_sdk.type.employee_filter import EmployeeFilter
from hi_bob_python_sdk.type.read_employees_request_reference_fields import ReadEmployeesRequestReferenceFields

class RequiredReadEmployeesRequestReference(TypedDict):
    pass

class OptionalReadEmployeesRequestReference(TypedDict, total=False):
    fields: ReadEmployeesRequestReferenceFields

    # Optional list of filters for filtering employees. We currently support up to one filter.
    filters: typing.List[EmployeeFilter]

    # <br>Optional field. <br>Default value = false. <br>Defines whether response should include inactive employees.
    showInactive: bool

    # Optional field.  <br> <b>If not sent:</b> supply machine-readable values only. <br> <br> Possible values: <br>  <br> <b>APPEND</b> - include the additional \"humanReadable\" JSON node in the response. <br>  <br> <b>REPLACE</b> - supply humanReadable values in JSON instead of machine-readable format. <br>
    humanReadable: str

class ReadEmployeesRequestReference(RequiredReadEmployeesRequestReference, OptionalReadEmployeesRequestReference):
    pass
