# coding: utf-8

"""
    Bob API

    Access your employees data with the Bob API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredReasonCode(TypedDict):
    pass

class OptionalReasonCode(TypedDict, total=False):
    id: int

    displayName: str

class ReasonCode(RequiredReasonCode, OptionalReasonCode):
    pass
