# coding: utf-8

"""
    Bob API

    Access your employees data with the Bob API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from hi_bob_python_sdk.type.reason_codes_names_reason_codes import ReasonCodesNamesReasonCodes

class RequiredReasonCodesNames(TypedDict):
    pass

class OptionalReasonCodesNames(TypedDict, total=False):
    reasonCodes: ReasonCodesNamesReasonCodes

class ReasonCodesNames(RequiredReasonCodesNames, OptionalReasonCodesNames):
    pass
