# coding: utf-8

"""
    Bob API

    Access your employees data with the Bob API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredStartDateUpdate(TypedDict):
    # The date this entry becomes effective.
    startDate: date

class OptionalStartDateUpdate(TypedDict, total=False):
    # Additional info for the start date update.
    reason: str

class StartDateUpdate(RequiredStartDateUpdate, OptionalStartDateUpdate):
    pass
