# coding: utf-8

"""
    Bob API

    Access your employees data with the Bob API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredTableEntry(TypedDict):
    # The date this entry becomes effective.
    effectiveDate: date

class OptionalTableEntry(TypedDict, total=False):
    # ID.
    id: int

    # The reason for this change.
    reason: str

class TableEntry(RequiredTableEntry, OptionalTableEntry):
    pass
